### ISSUE TITLE
PlatformException(ad_not_loaded, show failed for rewarded video..

### ISSUE THREAD

**Issue by darkdevelopers** [AndriousSolutions/ads#6]
Hello, first its great work. 
I get this message after call the second VideoAd. 

`2019-05-22 20:19:46.202017+0200 Runner[2112:383220] [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(ad_not_loaded, show failed for rewarded video, no ad was loaded, null)

#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)

#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
<asynchronous suspension>
#2      _invokeBooleanMethod (package:firebase_admob/firebase_admob.dart:521:61)
<asynchronous suspension>
#3      RewardedVideoAd.show (package:firebase_admob/firebase_admob.dart:392:12)
#4      Ads.showVideoAd (package:ads/ads.dart:289:17)
<asynchronous suspension>
#5      GameView.onTapDown (package:tap_cube/game/gameview.dart:46:9)
#6      TapGestureRecognizer._checkDown.<anonymous closure> (package:flutter/src/gestures/tap.dart:230:48)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
#8      TapGestureRecognizer._checkDown (package:flutter/src/gestures/tap.dart:230:9)
#9      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:209:7)
#10     GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:250:25)
#11     GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:231:31)
#12     _rootRun (dart:async/zone.dart:1120:38)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)`

I hope you can help me and thank you for the amazing software.

**Comment by Andrious** [comment]
Ah yes.  The infamous, "PlatformException(ad_not_loaded", error.
It appears to occur only 'while developing' in your IDE.  And always with the 'second attempt.'
Strange, isn't it.
It this, in fact, happening on a phone??  
In production?

I'll take a quick peek and see if they've resolved this issue.

Cheers.

**Comment by darkdevelopers** [comment]
I use the Android IDE, with the iPhone Xr simulator + in production iPhone X. 
The process to get this failure:
- The first Tap on the Button is working. 
- I close this Ad and Tap again on the Button to open a another ad, then you get this Platform Failure.

Flutter Doctor Log:

[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale de-DE)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.1)
[✓] Connected device (1 available)

**Comment by Andrious** [comment]
Fortunately, people have come up with a 'solution.'  
I've implemented the suggested changes and uploaded the latest package.
It's hoped you'll find version 0.4.2 will not produce that error now.

**Comment by oliverbytes** [comment]
I'm still getting this error on the latest version of Ads package and in Release Mode.

```
E/flutter (21324): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(ad_not_loaded, show failed for rewarded video, no ad was loaded, null)
E/flutter (21324): #0      StandardMethodCodec.decodeEnvelope 
package:flutter/…/services/message_codecs.dart:569
E/flutter (21324): #1      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:316
E/flutter (21324): <asynchronous suspension>
E/flutter (21324): #2      _invokeBooleanMethod 
package:firebase_admob/firebase_admob.dart:523
E/flutter (21324): <asynchronous suspension>
E/flutter (21324): #3      RewardedVideoAd.show 
package:firebase_admob/firebase_admob.dart:397
E/flutter (21324): #4      VideoAd.show 
package:ads/admob.dart:492
E/flutter (21324): #5      Ads.showVideoAd 
package:ads/ads.dart:418
E/flutter (21324): #6      AdManager.showFullScreenAd 
package:app/…/managers/ad.manager.dart:40
E/flutter (21324): #7      _StoriesViewerScreenState._spendToken 
package:app/…/screens/stories_viewer.screen.dart:111
E/flutter (21324): #8      _StoriesViewerScreenState.build._buildPageView.<anonymous closure> 
package:app/…/screens/stories_viewer.screen.dart:229
E/flutter (21324): #9      _PageViewState.build.<anonymous closure> 
package:flutter/…/widgets/page_view.dart:769
E/flutter (21324): #10     NotificationListener._dispatch 
package:flutter/…/widgets/notification_listener.dart:127
E/flutter (21324): #11     Notification.visitAncestor 
package:flutter/…/widgets/notification_listener.dart:45
E/flutter (21324): #12     ViewportNotificationMixin.visitAncestor 
package:flutter/…/widgets/scroll_notification.dart:31
E/flutter (21324): #13     Element.visitAncestorElements 
package:flutter/…/widgets/framework.dart:3509
E/flutter (21324): #14     Notification.dispatch 
package:flutter/…/widgets/notification_listener.dart:61
E/flutter (21324): #15     ScrollActivity.dispatchScrollUpdateNotification 
package:flutter/…/widgets/scroll_activity.dart:96
E/flutter (21324): #16     ScrollPosition.didUpdateScrollPositionBy 
package:flutter/…/widgets/scroll_position.dart:663
E/flutter (21324): #17     ScrollPosition.setPixels 
package:flutter/…/widgets/scroll_position.dart:219
E/flutter (21324): #18     ScrollPositionWithSingleContext.setPixels 
package:flutter/…/widgets/scroll_position_with_single_context.dart:83
E/flutter (21324): #19     DrivenScrollActivity._tick 
package:flutter/…/widgets/scroll_activity.dart:629
E/flutter (21324): #20     AnimationLocalListenersMixin.notifyListeners 
package:flutter/…/animation/listener_helpers.dart:124
E/flutter (21324): #21     AnimationController._tick 
package:flutter/…/animation/animation_controller.dart:768
E/flutter (21324): #22     Ticker._tick 
package:flutter/…/scheduler/ticker.dart:228
E/flutter (21324): #23     SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1033
E/flutter (21324): #24     SchedulerBinding.handleBeginFrame.<anonymous closure> 
package:flutter/…/scheduler/binding.dart:951
E/flutter (21324): #25     _LinkedHashMapMixin.forEach  (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (21324): #26     SchedulerBinding.handleBeginFrame 
package:flutter/…/scheduler/binding.dart:949
E/flutter (21324): #27     SchedulerBinding._handleBeginFrame 
package:flutter/…/scheduler/binding.dart:883
E/flutter (21324): #28     _rootRunUnary  (dart:async/zone.dart:1136:13)
E/flutter (21324): #29     _CustomZone.runUnary  (dart:async/zone.dart:1029:19)
E/flutter (21324): #30     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:931:7)
E/flutter (21324): #31     _invoke1  (dart:ui/hooks.dart:263:10)
E/flutter (21324): #32     _beginFrame  (dart:ui/hooks.dart:190:3)
E/flutter (21324):
```
